fr = open('data.txt','rb')
print('讀取位置',fr.tell())
print(fr.read())
print('讀取位置',fr.tell())
fr.seek(0)
print('讀取位置',fr.tell())
print(fr.read(3))
print('讀取位置',fr.tell())
print(fr.read(2))
print('讀取位置',fr.tell())
print(fr.read(3))
print('讀取位置',fr.tell())
fr.close()